title: John Kuo
description: 梦想仗剑走天涯，看看世间的繁华！
baseurl: ""
url:
permalink: slug
collections:
  apps:
    output: true
    permalink: /:title
    include: app-assets
defaults:
  - scope:
      path: ''
      type: 'apps'
    values:
      layout: 'app'
      type: 'app'
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
plugins:
  - jekyll-sitemap
strict_front_matter: true
